### ISSUE TITLE
Opening, exporting common file formats

### ISSUE THREAD

**Issue by morgannunan** [glimpse-editor/Glimpse#503]
I'm not sure what I'm doing wrong, but I'm running the AppImage of Glimpse and it will neither allow me to open common files, like png or jpeg, nor will it allow me to export in these formats. Opening simply returns 'unkown file type', and exporting returns 'The given filename does not have any known file extension.'

**Comment by TrechNex** [comment]
Thank you for reaching out to us. Can you confirm:
* Which Linux distro you're using
* When you downloaded the AppImage

The AppImage follows the tip of our dev branch so it tells us when we might have introduced breakage. If we know which distro you're using, it can help us troubleshoot and suggest a temporary workaround.

**Comment by TrechNex** [comment]
Okay, having looked into it: The AppImage builds from the dev branch. As a result, it doesn't include all the supplementary libraries needed to handle most file formats. That's because (as you can see from the [Downloads](https://glimpse-editor.github.io/downloads/) page) it's designed for development testing rather than production use.

As you are not the only person who's raised this, and the AppImageHub is not terribly clear about the fact this is a pre-release build, some time this week I will copy across those extra components from the beta builds.

**Comment by TrechNex** [comment]
Okay, having looked into it: The AppImage builds from the dev branch using the CI process. As a result, it doesn't include all the supplementary libraries needed to handle most file formats. That's because (as you can see from the [Downloads](https://glimpse-editor.github.io/downloads/) page) it's designed for development testing rather than production use.

I'm cc'ing @aferrerro2707 as it's possible the libraries are not being picked up from `AppImageBuilder.yml` correctly, as I did spot libjpg and libpng, so it's possible something has gone wrong with the build process.

**Comment by morgannunan** [comment]
Thanks. I'm running Ubuntu 20.04, and I'm running 43fff21, the latest AppImage updated 24 minutes ago.

**Comment by TrechNex** [comment]
Recategorising as a bug we should fix for 0.2.2. Technically the AppImage is working as designed, but the user expectation is that the AppImage should have feature parity with the Flatpak and Snap.

**Comment by TrechNex** [comment]
This was fixed in #510

**Comment by morgannunan** [comment]
I don't understand why this was closed. I followed the link to issue 510, and got the corresponding AppImage. The problem was not fixed. I also grabbed the latest AppImage from 10 days ago, and I can't open or save image files in that, either.

I followed the link in 510 to [the latest AppImage on the fork](https://github.com/azubieta/Glimpse/releases/tag/continuous), but this AppImage also does not allow me to open or export images.
